title: Hello World
description: 프로그램은 내가 원하는대로 움직이지 않는다. 타이핑대로 움직인다.
author: Park Songmi
avatar: /2.jpg
email: thdal1232@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
#
# google_analytics:

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
#
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: songmi
  card: summary
logo: logo.png
social:
  name: Park Songmi
  links:
    - https://github.com/songmi33
    - https://www.facebook.com/ngzhio
    - https://github.com/songmi33
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: ko
